# ARITHMATIC OPERATORS -- >
a = 10
b= 3
print(a+b)
print(a//b) # returns only the values before the decimal
print(a/b)

#IMPORTANT IN MODULUS
print(a%b) # return the reminder only
z = 4
y = 10
print(z%y)
# IF THE DIVISOR IS GREATOR THAN THE DIVIDEND(JISKO KAR RHE) THEN THE OUTPUT WILL BE THE DIVIDEND
print(a-b)


#ASSIGNMENT OPERATORS -->
A = 10
B = 4
A += B
print(A)
A -= B
print(A)
A *= B
print(A)
A /= B
print(A) 
A //= B
print(A)# This will not return 2 because as the value of A is 10.0 thats why the answer will be 2.0
A %= B
print(A)



#COMAPARISON OPERATORS -->
p = 10
q = 4
# print(p<q)
# print(p>q)
# print(p==q)
# print(p!=q)



#LOGICAL OPERATOR -->
print(True and False) # compare it with 
print(True and True)
print(True or False)
print(False or True)
print(False or False)
print(not(False))
print(not(True))

