 create database JodOrWot;
 use JodOrWot;
 create table Point(
 SCODE int(10),
 Name varchar(100),
 AGE integer(100),
 STRCDE int(200),
 POINTS int(10),
 GRADE varchar(2)
 );
insert into Point values(101,"Amit",16,1,6,14 );
insert into Point values(102,"Amit",13,3,4,56 );
insert into Point values(103,"Zaheer",14,2,1,NULL );
insert into Point values(105,"Gagan",15,5,2,55 );
insert into Point values(108,"Kumar",13,6,8,10 );
insert into Point values(109,"Rajesh",17,5,8,17);
insert into Point values(110,"Naveen",13,3,9,NULL);
insert into Point values(113,"Ajay",16,2,3,NULL );
insert into Point values(115,"Kapil",14,3,2,45 );
insert into Point values(120,"Gurdeep",15,2,6,NULL );
select * from Point;

 create table STREAM(
 STRCODE int(10),
 STRNAME varchar(20)
 );
ALTER TABLE STREAM drop column STRNAME;
ALTER TABLE STREAM ADD COLUMN STRNAME varchar(300);
insert into  STREAM values(1,"SCIENCE + COMP" );
insert into STREAM values(2,"SCIENCE + BIO" );
insert into STREAM values(3,"SCIENCE + ECO" );
insert into STREAM values(4,"COMMERCE + MATHS" );
insert into STREAM values(5,"COMMERCE + SOCIO" );
insert into STREAM values(6,"ARTS + MATHS" );
insert into STREAM values(7,"ARTS + SOCIO" );


-- --PERFORMING VARIOUS FUNCTIONS VARIOUS IN BOTH THE TABLES:
SELECT STRNAME FROM STREAM ORDER BY STRNAME;
SELECT COUNT(*) FROM POINT WHERE POINTS > 5;
UPDATE POINT SET GRADE = "A" WHERE POINTS>10;
SELECT GRADE FROM POINT WHERE POINTS>2;
delete FROM STREAM WHERE STRNAME ="ARTS + MATHS";
SELECT * FROM STREAM;
ALTER  TABLE STREAM RENAME COLUMN STRCODE to STRCDE;
SELECT* FROM STREAM;
SELECT NAME FROM POINT,STREAM WHERE POINT.STRCDE = STREAM.STRCDE AND STRNAME = "SCIENCE + COMPUTER";
UPDATE POINT SET GRADE = "A" WHERE POINTS>1;
SELECT * FROM POINT WHERE NAME LIKE "N%";
SELECT NAME from POINT,STREAM  WHERE POINT.STRCDE = STREAM.STRCDE AND STRNAME = "SCIENCE + COMP";





-- CREATING NEW TABLE COLLEGE AND PERFORMING VARIOUS FUNCTIONS OR  WOT-- 

 CREATE TABLE COLLEGE(NO INT(20),NAME VARCHAR(200), AGE INT(20),DEPARTMENT VARCHAR(200), DATEOFJOIN DATE, BASIC INT(200), SEX CHAR(2));
INSERT INTO COLLEGE VALUES(1,"SHALAZ",45,"BIOLOGY","13/02/20",10500,"M");
INSERT INTO COLLEGE VALUES(2,"SAMEERA",54,"BIOLOGY","10/01/30",9500,"F");
INSERT INTO COLLEGE VALUES(3,"YAGYEN",43,"PHYSICS","27/02/28",8500,"M");
INSERT INTO COLLEGE VALUES(4,"PRATYUSH",34,"CHEMISTRY","11/01/23",7500,"M");
INSERT INTO COLLEGE VALUES(5,"AREN",51,"MATHEMATICS","22/01/21",8500,"M");
INSERT INTO COLLEGE VALUES(6,"REETA",27,"CHEMISTRY","14/02/24",9000,"F");
INSERT INTO COLLEGE VALUES(7,"URVASHI",29,"BIOLOGY","10/02/23",8500,"F");
INSERT INTO COLLEGE VALUES(8,"TEENA",35,"MATHEMATICS","02/02/20",10500,"F");
INSERT INTO COLLEGE VALUES(9,"VIREN",49,"MATHEMATICS","03/01/28",9000,"M");
INSERT INTO COLLEGE VALUES(10,"PRAKASH",22,"PHYSICS","17/02/22",8000,"M");

-- --PERFORMING VARIOUS FUNCTIONS IN THE TABLE COLLEGE--  
SELECT * FROM COLLEGE;
UPDATE COLLEGE SET BASIC = '10500' WHERE AGE>50 AND DATEOFJOIN >"01/02/20";
SELECT * FROM COLLEGE;
SELECT NAME, AGE, BASIC FROM COLLEGE WHERE DEPARTMENT = "PHYSICS" OR DEPARTMENT = "CHEMISTRY";
DELETE FROM COLLEGE where NAME = "VIREN";
SELECT * FROM COLLEGE;
INSERT INTO COLLEGE VALUES(11,"SOURAV",50,"CHEMISTRY","18/05/24",12000,"M");
DESC COLLEGE;
SELECT * FROM COLLEGE;
SELECT NAME FROM COLLEGE ORDER BY BASIC desc;
SELECT SUM(BASIC) FROM COLLEGE GROUP BY DEPARTMENT;
SELECT * FROM COLLEGE WHERE BASIC NOT between 5000 AND 10000;
SELECT COUNT(NAME) FROM COLLEGE;
DELETE FROM COLLEGE WHERE DEPARTMENT = "bIOLOGY";
SELECT * FROM COLLEGE;
UPDATE COLLEGE SET DEPARTMENT = "BHADWA SUBJECT" WHERE DEPARTMENT = "MATHEMATICS";

SELECT * FROM COLLEGE WHERE BASIC IN (9000,10500);
SELECT * FROM COLLEGE;
RENAME TABLE COLLEGE TO NEWCOLLEGE;
SELECT * FROM NEWCOLLEGE;
RENAME TABLE NEWCOLLEGE TO COLLEGE;
DELETE  FROM COLLEGE WHERE DEPARTMENT = "pHYSICS";





 





